"""Init

Revision ID: 7a08d59dd8ef
Revises: d58bbe435a5b
Create Date: 2023-04-02 18:58:08.211911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a08d59dd8ef'
down_revision = 'd58bbe435a5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
